<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>markdown_render_test</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="LICENSE" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>
</Project>
