packages:
  - project/**
  - packages/**
  - .vscode/extensions/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - dprint
  - esbuild
  - less
  - sharp
  - unrs-resolver
  - workerd
