packages:
  - types
  - project/**
  - packages/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - dprint
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - workerd
