shellEmulator: true
shamefullyHoist: true
disallowWorkspaceCycles: true

packages:
  - apps/**
  - libs/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - workerd
