name: 'Setup Environment'
description: '初始化环境'

runs:
  using: composite
  steps:
    - name: 安装 pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 'latest'
        run_install: false

    - name: 安装 Node.js 环境
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: 安装 .NET Core 8.0 环境
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        cache: true
        cache-dependency-path: ./dotnet-packages/MarkdownRender/packages.lock.json

    - name: 还原 .NET 依赖
      working-directory: ./dotnet-packages
      run: dotnet restore ThaumaturgySpectacle.sln --locked-mode
      shell: bash

    - name: 安装 NodeJS 依赖
      run: pnpm install --frozen-lockfile
      shell: bash
