<Project>
	<PropertyGroup>
		<!-- 通用配置 -->
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net8.0</TargetFramework>
		<!-- 构建中间目录 -->
		<BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\.cache\dotnet-packages\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>
		<!-- 构建输出目录 -->
		<CustomBuildPath>$(MSBuildProjectDirectory)\dist\</CustomBuildPath>
		<OutputPath>$(CustomBuildPath)</OutputPath>
		<!-- 构建输出选项 -->
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<!-- 依赖锁文件 -->
		<RestoreLockedMode>true</RestoreLockedMode>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
	</PropertyGroup>
</Project>
