<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>MarkdownRender</RootNamespace>
		<NodeApiAssemblyJSModuleType>esm</NodeApiAssemblyJSModuleType>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Remove="node_modules\**" />
		<None Remove="node_modules\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="LICENSE" />
		<None Remove="package.json" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Markdig" Version="0.41.3" />
		<PackageReference Include="Microsoft.JavaScript.NodeApi.Generator" Version="0.9.12" />
	</ItemGroup>
</Project>
