name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 初始化环境
        uses: ./.ci/setup-env

      - name: 构建 wiki
        working-directory: ./project/content_processor
        run: NODE_ENV=production pnpm run build

      - name: 构建网站
        working-directory: ./project/website
        run: NODE_ENV=production pnpm run generate

      - name: 部署到 Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          command: pages deploy ./project/website/dist --project-name=thaumaturgy-spectacle
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
